# Generated by Django 5.2.14 on 2026-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('robot_type', models.CharField(default='AGV', max_length=50)),
                ('status', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('IDLE', 'IDLE'), ('MOVING', 'MOVING'), ('ERROR', 'ERROR')], default='OFFLINE', max_length=20)),
                ('battery_level', models.FloatField(default=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
