# Generated by Django 5.2.14 on 2026-05-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BATTERY_LOW', 'BATTERY_LOW'), ('ROBOT_ONLINE', 'ROBOT_ONLINE'), ('ROBOT_OFFLINE', 'ROBOT_OFFLINE'), ('MISSION_STARTED', 'MISSION_STARTED'), ('MISSION_COMPLETED', 'MISSION_COMPLETED'), ('ERROR', 'ERROR')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='robots.robot')),
            ],
        ),
    ]
